version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "weekday"
      time: "04:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "/"
    ignore:
      - dependency-name: "typeahead.js"
    assignees:
      - "frank.paczynski"
