---

run e2e tests:
  stage: e2e
  image: gitlab.open-xchange.com:4567/frontend/dev_env/puppeteer:puppeteer
  variables:
    LAUNCH_URL: http://e2e-develop.ui.cloud.open-xchange.com/appsuite/
    PROVISIONING_URL: http://e2e-develop.ui.cloud.open-xchange.com/
    CONTEXT_ID: $CI_JOB_ID
    CHROME_ARGS: '--no-sandbox'
    PARTITIONS: '@shaky ^Accessibility ^Contacts ^Login ^Mail\sCompose ^Calendar.(?!>\sImport|>\sCreate) ^Calendar.(?=>\sImport|>\sCreate) ^Mail\s> ^Drive ^Portal ^Sharing ^General ^Settings ^Tasks ^Mailfilter'
  script:
    # make PARTITIONS an array
    - PARTITIONS=(${PARTITIONS})
    - cd ui
    - yarn --non-interactive --no-progress -s --cache-folder ../.yarn-cache
    # on node 1 run shaky tests. Never fail the pipeline
    # - '[ "$CI_NODE_INDEX" -eq "1" ] && yarn e2e -g "${PARTITION[${CI_NODE_INDEX} - 1]}" || true'
    # read this like: this is node x (with x not being 1) -- run tests selected for this node -- return the result of testrun only for the current node
    # RegEx: Starts with one of the trigger words of the list, but does not contain @shaky anywhere
    - PATTERN=${PARTITIONS[$CI_NODE_INDEX - 1]}
    - if [ ${CI_NODE_INDEX} -ne "1" ]; then PATTERN+="\s?((?!"; PATTERN+=${PARTITIONS[0]}; PATTERN+=").)*$"; fi;
    - yarn e2e -g "$PATTERN" || [ "$CI_NODE_INDEX" -eq "1" ];
  tags:
    - kubernetes
  parallel: 15
  artifacts:
    when: always
    paths:
      - ui/build/e2e/
    expire_in: 1 day
  only:
    changes:
      - ui/**/*
  except:
    refs:
      - /^poc\//
