---

stages:
  - test
  - deploy
  - cleanup

delete project on obs:
  image: gitlab.open-xchange.com:4567/frontend/osc_env:latest
  stage: cleanup
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo "${OBS_OSCRC}" >> ~/.oscrc
  script:
    - echo ${CI_COMMIT_REF_SLUG} | grep -e "^master" -e "^release" && export OBS_PROJECT=frontend-${CI_COMMIT_REF_NAME} || export OBS_PROJECT=frontend-${CI_COMMIT_REF_SLUG}
    - osc rdelete -r ${OBS_PROJECT} -m "GitLab CI environment stopped"
  environment:
    name: packages/$CI_COMMIT_REF_NAME
    action: stop
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_REF_NAME !~ /^e2e\//'
      when: manual
      allow_failure: true

upload:
  image: gradle:5.6.2-jre8
  stage: deploy
  variables:
    OBS_PROJECT_EXT: $CI_COMMIT_REF_SLUG
  timeout: 20m
  script:
    # only run subtasks for projects which have been build previously (contain some built project files)
    - export TASKS=$(ls */build/pkg -d | sed -E "s,([^\/ ]+)\/[^ ]+,:\1:upload,g")
    - test -n "$TASKS" && export TASKS="$TASKS wait4Project"
    - gradle --no-daemon $TASKS
  environment:
    name: packages/$CI_COMMIT_REF_NAME
    on_stop: "delete project on obs"
    url: https://buildservice.open-xchange.com/frontend-$CI_COMMIT_REF_SLUG/
  dependencies:
    - build ui
    - build update-themes
    - build help
    - build guidedtours
    - build spamexperts
    - build dynamic-theme
  rules:
    - if: '$FORCE_PACKAGE_UPLOAD == "true"'
      when: always
      allow_failure: true
    - if: '$CI_COMMIT_TAG || $CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_REF_NAME !~ /^(e2e\/.*|master-?.*|release-.*|develop)$/'
      when: manual
      allow_failure: true

upload stable:
  extends: upload
  variables:
    OBS_PROJECT_EXT: $CI_COMMIT_REF_NAME
  environment:
    name: packages/$CI_COMMIT_REF_NAME
    on_stop: "delete project on obs"
    url: https://buildservice.open-xchange.com/frontend-$CI_COMMIT_REF_NAME/
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_NAME =~ /^(master-?.*|develop|release-.*|.*DOCS-.*)$/'
      when: on_success
      allow_failure: true

# notify documents projects about changes to allow
# dependent builds and testing
triggerappsuite:
  extends: upload
  script:
    - "curl -X POST -F token=686e6e702ab5da776a699d39d4b4c7 -F ref=develop -F \"variables[CWS]=$CI_COMMIT_REF_NAME\" -F \"variables[GIT_REPO]=$CI_PROJECT_URL\" -F \"variables[GITLAB_ID]=$CI_PROJECT_ID\" https://gitlab.open-xchange.com/api/v4/projects/1021/trigger/pipeline"
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_NAME =~ /^(master-?.*|develop|release-.*|.*DOCS-.*)$/'
      when: on_success
      allow_failure: true
