---

stages:
  - deploy
  - cleanup

deploy preview app:
  stage: deploy
  dependencies: []
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: docker.ui.cloud.open-xchange.com
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    SERVER: http://10.50.0.18/appsuite/
  script:
    - docker pull $DOCKER_IMAGE
    - docker stop $CI_COMMIT_REF_SLUG || echo "Nothing to stop"
    - counter=0; while [ $counter -lt 10 ]; do sleep 2; docker run --name $CI_COMMIT_REF_SLUG --rm -d -e SERVER=$SERVER $DOCKER_IMAGE && break || counter=$((counter+1)); done
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.ui.cloud.open-xchange.com/appsuite/
    on_stop: stop_review
  only:
    - /^feature\//
    - /^bug\//
    - /^poc\//

stop_review:
  stage: cleanup
  dependencies: []
  variables:
    GIT_STRATEGY: none
    DOCKER_HOST: docker.ui.cloud.open-xchange.com
  script:
    - docker stop $CI_COMMIT_REF_SLUG
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - /^feature\//
    - /^bug\//
    - /^poc\//
